import React from 'react';

var order = <span>Order</span>;
var zeal = <span>Zeal</span>;
var shield = <span>Shield</span>;
var spawn = <span>Spawn</span>;
var melee = <span>Melee</span>;
var ranged = <span>Ranged</span>;
var deploy = <span>Deploy</span>;
var banish = <span>Banish</span>;
var summon = <span>Summon</span>;
var armor = <span>Armor</span>;
var create = <span>Create</span>;
var deathblow = <span>Deathblow</span>;
var purify = <span>Purify</span>;
var cooldown = <span>Cooldown</span>;
var defender = <span>Defender</span>;
var charge = <span>Charge</span>;
var immunity = <span>Immunity</span>;
var seize = <span>Seize</span>;
var barricade = <span>Barricade</span>;
var vitality = <span>Vitality</span>;
var bleeding = <span>Bleeding</span>;
var heal = <span>Heal</span>;
var poison = <span>Poison</span>;
var exposed = <span>Exposed</span>;


var deathwish = <span>Deathwish</span>;
var dominance = <span>Dominance</span>;
var thrive = <span>Thrive</span>;
var consume = <span>Consume</span>;

var reveal = <span>Reveal</span>;

var formation = <span>Formation</span>;
var inspired = <span>Inspired</span>;
var duel = <span>Duel</span>;
var crew = <span>Crew</span>;
var resupply = <span>Resupply</span>;

var lock = <span>Lock</span>;

var resilience = <span>Resilience</span>;
var spring = <span>Spring</span>;
var ambush = <span>Ambush</span>;

var discard = <span>Discard</span>;
var berserk = <span>Berserk</span>
var bloodthirst = <span>Bloodthirst</span>

var coins = <span>Coins</span>;
var bounty = <span>Bounty</span>;
var tribute = <span>Tribute</span>;
var intimidate = <span>Intimidate</span>;
var profit = <span>Profit</span>;
var fee = <span>Fee</span>;
var hoard = <span>Hoard</span>;
var insanity = <span>Insanity</span>;
var bonded = <span>Bonded</span>;

const CARD_INFO_ARRAY = [
	// STRATEGY
	{	name: "Tactical Advantage",
		prov: "",
		type: "strategy",
		faction: "neutral",
		border: "gold",
		legendary: true,
		src: "tacticalAdvantage.mp4",
		tooltip: <p>{order}: Boost an allied unit by 5, then Banish self.</p>
	},
	{	name: "Cursed Scroll",
		prov: "",
		type: "strategy",
		faction: "neutral",
		border: "gold",
		legendary: true,
		src: "cursedScroll.mp4",
		tooltip: <p>{order}: Look at the top 3 cards from your deck and draw one of them, then put a card from your hand at the bottom of your deck.</p>
	},
	{	name: "Urn of Shadows",
		prov: "",
		type: "strategy",
		faction: "monsters",
		border: "gold",
		legendary: true,
		src: "urnShadows.mp4",
		tooltip: <p>{order}: Trigger a bronze allied unit's {deathwish} ability.</p>
	},
	{	name: "Collar",
		prov: "",
		type: "strategy",
		faction: "nilfgaard",
		border: "gold",
		legendary: true,
		src: "collar.mp4",
		tooltip: <p>{order}: {lock} an enemy unit and damge it by 3.</p>
	},
	{	name: "Engineering solution",
		prov: "",
		type: "strategy",
		faction: "northern",
		border: "gold",
		legendary: true,
		src: "engineering.mp4",
		tooltip: <p>{order}: Boost an allied unit by 3 and give it {shield}.</p>
	},
	{	name: "Aen Seidhe Sabre",
		prov: "",
		type: "strategy",
		faction: "scoiatael",
		border: "gold",
		legendary: true,
		src: "aenSeidhe.mp4",
		tooltip: <p>{order}: {spawn} and play Scoia'tael Neophyte.</p>
	},
	{	name: "Mask of Uroboros",
		prov: "",
		type: "strategy",
		faction: "skellige",
		border: "gold",
		legendary: true,
		src: "maskUroboros.mp4",
		tooltip: <p>{order}: Draw a card then {discard} a card.</p>
	},
	{	name: "Tiger's Eye",
		prov: "",
		type: "strategy",
		faction: "syndicate",
		border: "gold",
		legendary: true,
		src: "tigersEye.mp4",
		tooltip: <p>{order}: Gain 4 {coins}.</p>
	},



	{	name: "Siege",
		prov: "pp14",
		type: "artifact",
		faction: "northern",
		border: "gold",
		legendary: true,
		src: "siege.mp4",
		tooltip: <p>Scenario: Progress whenever you play a Siege Engine.<br/>Prologue: {spawn} a Reinforced Trebuchet in your Ranged row.<br/>Chapter 1: {spawn} a Battering Ram in your Ranged row.<br/>Chapter 2: {spawn} and play Bombardment.</p>
	},
	{	name: "Masquerade Ball",
		prov: "pp14",
		type: "artifact",
		faction: "nilfgaard",
		border: "gold",
		legendary: true,
		src: "ball.mp4",
		tooltip: <p>Scenario: Progress whenever you play an Aristocrat.<br/>Prologue: {spawn} a Thirsty Dame in this row.<br/>Chapter 1: {spawn} and play Fangs of the Empire.<br/>Chapter 2: {spawn} and play Fangs of the Empire.</p>
	},
	{	name: "Passiflora",
		prov: "pp14",
		type: "artifact",
		faction: "syndicate",
		border: "gold",
		legendary: true,
		src: "passiflora.mp4",
		tooltip: <p>Scenario: Progress whenever you play a Blindeye.<br/>Prologue: {spawn} a Sly Seductress in this row.<br/>Chapter 1: {spawn} Passiflora Peaches in this row.<br/>Chapter 2: Gain 6 {coins}.</p>
	},



	{	name: "Iorveth's Gambit",
		prov: "pp13",
		type: "special",
		faction: "scoiatael",
		border: "gold",
		legendary: true,
		src: "iorveth.mp4",
		tooltip: <p>If you have 4 or more Traps in your starting deck, play 2 of them at random.</p>
	},
	{	name: "Haunt",
		prov: "pp13",
		type: "artifact",
		faction: "monsters",
		border: "gold",
		legendary: true,
		src: "haunt.mp4",
		tooltip: <p>Scenario: Progress whenever you play a unit with {deathwish}.<br/>Prologue: {spawn} a Desert Banshee in this row.<br/>Chapter 1: {spawn} and play a Barghest.<br/>Chapter 2: {spawn} and play a Nightwraith.</p>
	},
	{	name: "Feign Death",
		prov: "pp13",
		type: "artifact",
		faction: "scoiatael",
		border: "gold",
		legendary: true,
		src: "feignDeath.mp4",
		tooltip: <p>Scenario: Progress whenever you play a an Elf.<br/>Prologue: {spawn} an Elven Deadeye in this row.<br/>Chapter 1: {spawn} 2 Elven Deadeyes in this row.<br/>Chapter 2: {spawn} and play Waylay.</p>
	},
	{	name: "Gedyneith",
		prov: "pp13",
		type: "artifact",
		faction: "skellige",
		border: "gold",
		legendary: true,
		src: "gedyneith.mp4",
		tooltip: <p>Scenario: Progress whenever you play a Druid.<br/>Prologue: {spawn} a Crow Clan Preacher in this row.<br/>Chapter 1: {spawn} and play Crow's-eye Rhizome.<br/>Chapter 2: {spawn} and play Mardroeme.</p>
	},
	{	name: "Keltullis",
		prov: "pp13",
		type: "unit",
		strength: "9",
		faction: "monsters",
		border: "gold",
		legendary: true,
		src: "keltullis.mp4",
		tooltip: <p>{melee}: Every allied turn, an turn end, destroy the lowest unit on the side with the most units.</p>
	},
	{	name: "Draug",
		prov: "pp13",
		type: "unit",
		strength: "7",
		faction: "northern",
		border: "gold",
		legendary: true,
		src: "draug.mp4",
		tooltip: <p>{deploy}: Transform all allied Human units in this row into Kaedweni Revenants, without changing their power.</p>
	},
	{	name: "The Great Oak",
		prov: "pp13",
		type: "unit",
		strength: "7",
		faction: "scoiatael",
		border: "gold",
		legendary: true,
		src: "oak.mp4",
		tooltip: <p>{deploy}: Damage an enemy unit by the number of cards to the left of Great Oak, then boost self by number of cards to the right of Great Oak.</p>
	},
	{	name: "phoenix",
		prov: "pp13",
		type: "unit",
		strength: "4",
		faction: "neutral",
		border: "gold",
		legendary: true,
		src: "phoenix.mp4",
		tooltip: <p>On round start, if Phoenix is your graveyard, {banish} it, then {spawn} Phoenix Hatchling and {summon} it to a random allied row.</p>
	},
	{	name: "Regis",
		prov: "pp13",
		type: "unit",
		strength: "2",
		faction: "neutral",
		border: "gold",
		legendary: true,
		src: "regis.mp4",
		tooltip: <p>{deploy}: Damage all enemy units on a row by 1. If any were destroyed, repeat this ability.</p>
	},



	{	name: "Ragh Nar Roog",
		prov: "pp12",
		type: "special",
		faction: "neutral",
		border: "gold",
		legendary: true,
		src: "raghnarroog.mp4",
		tooltip: <p>Apply this Row Effect: Every enemy turn, on turn start, damage the highest unit on this row by 2.</p>
	},
	{	name: "Water of Brokilon",
		prov: "pp12",
		type: "special",
		faction: "scoiatael",
		border: "gold",
		legendary: true,
		src: "water.mp4",
		tooltip: <p>{spawn} 2 Dryad Fledglings into the row.</p>
	},
	{	name: "Hemdall",
		prov: "pp12",
		type: "unit",
		strength: "8",
		faction: "skellige",
		border: "gold",
		legendary: true,
		src: "hemdall.mp4",
		tooltip: <p>{deploy}: Deal 1 damage to random enemy units in a row, multiplied by the number of units in that row.</p>
	},
	{	name: "Imlerith",
		prov: "pp12",
		type: "unit",
		strength: "7",
		faction: "monsters",
		border: "gold",
		legendary: true,
		src: "imlerith.mp4",
		tooltip: <p>{deploy}: Set an allied unit's power to 7.<br/>{dominance}: Set a unit's power to 7 instead.</p>
	},
	{	name: "Plague Maiden",
		prov: "pp12",
		type: "unit",
		strength: "7",
		faction: "monsters",
		border: "gold",
		legendary: true,
		src: "maiden.mp4",
		tooltip: <p>{deathwish}: {spawn} 7 Rats in this row.</p>
	},
	{	name: "Professor",
		prov: "pp12",
		type: "unit",
		strength: "6",
		faction: "syndicate",
		border: "gold",
		legendary: true,
		src: "professor.mp4",
		tooltip: <p>{deploy}: Put a {bounty} on an enemy unit and damage it by 3.<br/>{tribute} 3: Ignore a target's {armor}.</p>
	},
	{	name: "Vernossiel",
		prov: "pp12",
		type: "unit",
		strength: "5",
		faction: "scoiatael",
		border: "gold",
		legendary: true,
		src: "vernossiel.mp4",
		tooltip: <p>{deploy} ({melee}): Each allied Elven Deadeye damages a random enemy unit by 2.<br/>{deploy} ({ranged}): {spawn} 2 Elven Deadeyes in this row.</p>
	},
	{	name: "Roche: Merciless",
		prov: "pp12",
		type: "unit",
		strength: "4",
		faction: "northern",
		border: "gold",
		legendary: true,
		src: "roche.mp4",
		tooltip: <p>{deploy}: Damage an enemy unit by 2.<br/>{deathblow}: Gain {zeal}.<br/>{order}: {spawn} a Blue Stripes Commando and {summon} it to this row.</p>
	},
	{	name: "Wild Boar of the Sea",
		prov: "pp12",
		type: "unit",
		strength: "4",
		faction: "skellige",
		border: "gold",
		legendary: true,
		src: "boar.mp4",
		tooltip: <p>{deploy} ({melee}): Damage all damaged enemy units by 1, then damage all enemy units by 1.</p>
	},
	{	name: "Tinboy",
		prov: "pp12",
		type: "unit",
		strength: "4",
		faction: "syndicate",
		border: "gold",
		legendary: true,
		src: "tinboy.mp4",
		tooltip: <p>{deploy}: Damage all enemy units on a row by 2.<br/>{tribute} 8: Damge all enemy units by 2 instead.</p>
	},
	{	name: "Syanna",
		prov: "pp12",
		type: "unit",
		strength: "3",
		faction: "neutral",
		border: "gold",
		legendary: true,
		src: "syanna.mp4",
		tooltip: <p>{order}: Repeat the {deploy} ability of the next unit you play during this turn.</p>
	},



	{	name: "Uma's Curse",
		prov: "pp11",
		type: "special",
		faction: "neutral",
		border: "gold",
		legendary: true,
		src: "uma.mp4",
		tooltip: <p>{create} and play a gold unit from any faction.</p>
	},
	{	name: "Collusion",
		prov: "pp11",
		type: "special",
		faction: "syndicate",
		border: "gold",
		legendary: true,
		src: "collusion.mp4",
		tooltip: <p>If you control a unit with the gang category:<br/>Blindeyes - Increase all other effects by 1.<br/>Crownsplitters - Boost an allied unit with the lowest power by 4.<br/>Cutups - Damage an enemy unit with the highest power by 4.<br/>Firesworn - {spawn} 2 Firesworn Zealot in a random allied row.<br/>Tidecloaks - Gain 3 {coins}.</p>
	},
	{	name: "Olaf",
		prov: "pp11",
		type: "unit",
		strength: "8",
		faction: "skellige",
		border: "gold",
		legendary: true,
		src: "olaf.mp4",
		tooltip: <p>{order}: Boost Olaf by twice the amount he is damaged.</p>
	},
	{	name: "Damien de la Tour",
		prov: "pp11",
		type: "unit",
		strength: "5",
		faction: "nilfgaard",
		border: "gold",
		legendary: true,
		src: "damien.mp4",
		tooltip: <p>{order} (melee): Re-enable your Leader's ability.</p>
	},
	{	name: "Vincent Van Moorlehem",
		prov: "pp11",
		type: "unit",
		strength: "5",
		faction: "nilfgaard",
		border: "gold",
		legendary: true,
		src: "vincent.mp4",
		tooltip: <p>{deploy}: Destroy an enemy unit with status.</p>
	},
	{	name: "Ithlinne Aegli",
		prov: "pp11",
		type: "unit",
		strength: "5",
		faction: "scoiatael",
		border: "gold",
		legendary: true,
		src: "aegli.mp4",
		tooltip: <p>{deploy}: Boost a Scoia'tael unit in your hand by 4.</p>
	},
	{	name: "Ruhin",
		prov: "pp11",
		type: "unit",
		strength: "4",
		faction: "monsters",
		border: "gold",
		legendary: true,
		src: "ruhin.mp4",
		tooltip: <p>{deathwish}: On allied turn end, {summon} this unit from your graveyard to a random allied row.</p>
	},
	{	name: "Queen Adalia",
		prov: "pp11",
		type: "unit",
		strength: "3",
		faction: "northern",
		border: "gold",
		legendary: true,
		src: "adalia.mp4",
		tooltip: <p>{deploy}: {spawn} and play a base copy of a bronze unit from your hand, then give it a {shield}.</p>
	},
	{	name: "Avallac'h: Sage",
		prov: "pp11",
		type: "unit",
		strength: "1",
		faction: "neutral",
		border: "gold",
		legendary: true,
		src: "avallac.mp4",
		tooltip: <p>{deploy} {ranged}: Play an artifact from your deck.</p>
	},



	{	name: "Karathi Heatwave",
		prov: "p10",
		type: "special",
		faction: "neutral",
		border: "gold",
		legendary: true,
		src: "heatwave.mp4",
		tooltip: <p>{banish} a unit or an artifact.</p>
	},
	{	name: "Royal Decree",
		prov: "p10",
		type: "special",
		faction: "neutral",
		border: "gold",
		legendary: true,
		src: "decree.mp4",
		tooltip: <p>Play a unit from your deck.</p>
	},
	{	name: "Ritual Sacrifice",
		prov: "p10",
		type: "special",
		faction: "monsters",
		border: "gold",
		legendary: true,
		src: "ritual.mp4",
		tooltip: <p>Trigger all allied units Deathwish abilities.</p>
	},
	{	name: "Call of the Forest",
		prov: "p10",
		type: "special",
		faction: "scoiatael",
		border: "gold",
		legendary: true,
		src: "call.mp4",
		tooltip: <p>Play a Scoia'tael unit from your deck and boost it by 1.</p>
	},
	{	name: "Sacred Flame",
		prov: "p10",
		type: "artifact",
		faction: "syndicate",
		border: "gold",
		legendary: true,
		src: "sacredFlame.mp4",
		tooltip: <p>{deploy}: {spawn} a Firesworn Zealot and {summon} it on both sides of this card. Whenever you {spawn} a unit, boost it by 1.</p>
	},
	{	name: "Yghern",
		prov: "p10",
		type: "unit",
		strength: "13",
		faction: "monsters",
		border: "gold",
		legendary: true,
		src: "yghern.mp4",
		tooltip: <p>{deploy}: Gain {armor} equal to the number of cards in your hand.<br/>If this unit has no {armor}, destroy self.</p>
	},
	{	name: "Barnabas Beckenbauer",
		prov: "p10",
		type: "unit",
		strength: "6",
		faction: "scoiatael",
		border: "gold",
		epic: true,
		src: "barnabas.mp4",
		tooltip: <p>{deploy}: Boost an allied Elf, Dwarf, and Dryad unit by 2.</p>
	},
	{	name: "Dettlaff: Higher Vampire",
		prov: "p10",
		type: "unit",
		strength: "5",
		faction: "monsters",
		border: "gold",
		legendary: true,
		src: "dettlaff.mp4",
		tooltip: <p>{deathwish}: {summon} this unit from the graveyard to same row.<br/>This unit's ability is limited to 2 uses and does not refresh when it leaves the battlefield.</p>
	},
	{	name: "Stefan Skellen",
		prov: "p10",
		type: "unit",
		strength: "5",
		faction: "nilfgaard",
		border: "gold",
		legendary: true,
		src: "stefan.mp4",
		tooltip: <p>{order} ({ranged}): {spawn} and play a copy of the last Tactic card you played this round.</p>
	},
	{	name: "Letho",
		prov: "p10",
		type: "unit",
		strength: "5",
		faction: "nilfgaard",
		border: "gold",
		legendary: true,
		src: "letho.mp4",
		tooltip: <p>{deploy}: Transform into a copy of another unit on the battlefield without changing power.</p>
	},
	{	name: "Morkvarg: Heart of Terror",
		prov: "p10",
		type: "unit",
		strength: "5",
		faction: "skellige",
		border: "gold",
		legendary: true,
		src: "morkvarg.mp4",
		tooltip: <p>{deploy}: Damage an enemy unit by 1. Repeat until target is damaged.</p>
	},
	{	name: "Ihuarraquax",
		prov: "p10",
		type: "unit",
		strength: "4",
		faction: "neutral",
		border: "gold",
		legendary: true,
		src: "ihuarraquax.mp4",
		tooltip: <p>{deploy} ({melee}): Each player {summon} the unit with the highest Provision Cost from their deck to the melee row.<br/>{deploy} ({ranged}): Each player {summon} the unit with the lowest Provision Cost from their deck to the ranged row.</p>
	},
	{	name: "Vesemir: Mentor",
		prov: "p10",
		type: "unit",
		strength: "4",
		faction: "neutral",
		border: "gold",
		legendary: true,
		src: "vesemir.mp4",
		tooltip: <p>{deploy}: Boost all allied Witcher units in hand, deck, and on the battlefield by 1.</p>
	},
	{	name: "Prince Anseis",
		prov: "p10",
		type: "unit",
		strength: "4",
		faction: "northern",
		border: "gold",
		legendary: true,
		src: "anseis.mp4",
		tooltip: <p>{formation}.<br/>{order}: Damage an enemy unit by 4.<br/>{inspired}: {duel} an enemy unit instead.</p>
	},
	{	name: "Hjalmar an Craite",
		prov: "p10",
		type: "unit",
		strength: "3",
		faction: "skellige",
		border: "gold",
		legendary: true,
		src: "hjalmar.mp4",
		tooltip: <p>{deploy} ({melee}): {banish} a unit in your graveyard and damage an enemy unit by its power.</p>
	},
	{	name: "Carlo Varese",
		prov: "p10",
		type: "unit",
		strength: "3",
		faction: "syndicate",
		border: "gold",
		epic: true,
		src: "carlo.mp4",
		tooltip: <p>{deploy} ({melee}): Damage an enemy unit by 1 for each card in your hand.</p>
	},



	{	name: "Merigold's Hailstorm",
		prov: "p9",
		type: "special",
		faction: "neutral",
		border: "gold",
		epic: true,
		src: "hailstorm.mp4",
		tooltip: <p>Damage 5 enemy units by 2.</p>
	},
	{	name: "Naglfar",
		prov: "p9",
		type: "special",
		faction: "monsters",
		border: "gold",
		legendary: true,
		src: "naglfar.mp4",
		tooltip: <p>Look at 2 random gold cards from your deck, then play one and place the other on top.</p>
	},
	{	name: "Yennefer's Inuocation",
		prov: "p9",
		type: "special",
		faction: "nilfgaard",
		border: "gold",
		legendary: true,
		src: "yennefer.mp4",
		tooltip: <p>Place an enemy unit at the top of your deck.</p>
	},
	{	name: "Sigrdrifa's Rite",
		prov: "p9",
		type: "special",
		faction: "skellige",
		border: "gold",
		epic: true,
		src: "rite.mp4",
		tooltip: <p>{summon} a Skellige unit from your graveyard into an allied row.</p>
	},
	{	name: "Tainted Ale",
		prov: "p9",
		type: "artifact",
		faction: "neutral",
		border: "gold",
		epic: true,
		src: "ale.mp4",
		tooltip: <p>{zeal}.<br/>{order}: Damage a unit by 2.<br/>{charge}: 3.</p>
	},
	{	name: "Tibor Eggebracht",
		prov: "p9",
		type: "unit",
		strength: "13",
		faction: "nilfgaard",
		border: "gold",
		legendary: true,
		src: "tibor.mp4",
		tooltip: <p>{deploy}: Your opponent {summon} the top unit from their deck to a randomenemy row.</p>
	},
	{	name: "Caretaker",
		prov: "p9",
		type: "unit",
		strength: "7",
		faction: "neutral",
		border: "gold",
		legendary: true,
		src: "caretaker.mp4",
		tooltip: <p>{zeal}. {order}: {purify} a unit. {cooldown}: 2.</p>
	},
	{	name: "Aguara",
		prov: "p9",
		type: "unit",
		strength: "7",
		faction: "neutral",
		border: "gold",
		legendary: true,
		src: "aguara.mp4",
		tooltip: <p>{deploy} ({melee}): {lock} a unit. {deploy} (ranged): Remove a unit's {lock}.</p>
	},
	{	name: "Donimir of Troy",
		prov: "p9",
		type: "unit",
		strength: "7",
		faction: "northern",
		border: "gold",
		legendary: true,
		src: "donimir.mp4",
		tooltip: <p>{defender}. {shield}.</p>
	},
	{	name: "Madame Luiza",
		prov: "p9",
		type: "unit",
		strength: "6",
		faction: "syndicate",
		border: "gold",
		legendary: true,
		src: "luiza.mp4",
		tooltip: <p>{intimidate}.<br/>{deploy}: Your next {tribute} this round is free.</p>
	},
	{	name: "Savolla",
		prov: "p9",
		type: "unit",
		strength: "6",
		faction: "syndicate",
		border: "gold",
		legendary: true,
		src: "savolla.mp4",
		tooltip: <p>{profit} 2.<br/>{tribute} 9: {spawn} a Savolla's Frightener in this row.</p>
	},
	{	name: "Vilgefortz",
		prov: "p9",
		type: "unit",
		strength: "5",
		faction: "nilfgaard",
		border: "gold",
		legendary: true,
		src: "vilgefortz.mp4",
		tooltip: <p>{deploy} ({melee}): Destroy an enemy unit, then your opponent {summon} the top unit from their deck to a random enemy row.<br/>{deploy} ({ranged}): Destroy an allied unit, then {summon} the top unit from your deck to a random allied row.</p>
	},
	{	name: "Seltkirk of Gulet",
		prov: "p9",
		type: "unit",
		strength: "5",
		faction: "northern",
		border: "gold",
		legendary: true,
		src: "seltkirk.mp4",
		tooltip: <p>{order} ({melee}): {duel} an enemy unit.</p>
	},
	{	name: "Gabor Zigrin",
		prov: "p9",
		type: "unit",
		strength: "5",
		faction: "scoiatael",
		border: "gold",
		legendary: true,
		src: "gabor.mp4",
		tooltip: <p>{deploy} ({melee}): Gain {resilience}.<br/>{deploy} ({ranged}): Gain {immunity}.<br/>Whenever you play Dwarf, boost self by 1.</p>
	},
	{	name: "Figgis Merluzzo",
		prov: "p9",
		type: "unit",
		strength: "5",
		faction: "scoiatael",
		border: "gold",
		legendary: true,
		src: "merluzzo.mp4",
		tooltip: <p>{defender}.<br/>{deploy}: {spawn} Rowdy Dwarf in this row.</p>
	},
	{	name: "Artis",
		prov: "p9",
		type: "unit",
		strength: "5",
		faction: "skellige",
		border: "gold",
		legendary: true,
		src: "artis.mp4",
		tooltip: <p>{ranged}: Whenever a unit is played, damage it by half its current power.</p>
	},
	{	name: "Vildkaarl",
		prov: "p9",
		type: "unit",
		strength: "5",
		faction: "skellige",
		border: "gold",
		epic: true,
		src: "vildkaarl.mp4",
		tooltip: <p>{berserk} 2: Transform into a Champion of Swalblod.</p>
	},
	{	name: "Miruna",
		prov: "p9",
		type: "unit",
		strength: "4",
		faction: "monsters",
		border: "gold",
		legendary: true,
		src: "miruna.mp4",
		tooltip: <p>{deathwish}: {seize} an enemy unit with 4 or less power.</p>
	},
	{	name: "Moreelse",
		prov: "p9",
		type: "unit",
		strength: "4",
		faction: "syndicate",
		border: "gold",
		legendary: true,
		src: "moreelse.mp4",
		tooltip: <p>{deploy}: Damage an enemy unit by 4.<br/>{tribute} 6: Destroy it instead.</p>
	},
	{	name: "Vrygheff",
		prov: "p9",
		type: "unit",
		strength: "3",
		faction: "nilfgaard",
		border: "gold",
		epic: true,
		src: "vrygheff.mp4",
		tooltip: <p>{deploy}: Trigger the {deploy} abilities of adjacent bronze Soldiers.</p>
	},

	{	name: "Imlerith's Wrath",
		prov: "p8",
		type: "special",
		faction: "monsters",
		border: "gold",
		legendary: true,
		src: "wrath.mp4",
		tooltip: <p>Damage an enemy unit by the power og your highest allied unit.<br/>If you control Imlerith, destroy an enemy unit instead.</p>
	},
	{	name: "Bribery",
		prov: "p8",
		type: "special",
		faction: "nilfgaard",
		border: "gold",
		legendary: true,
		src: "bribery.mp4",
		tooltip: <p>{create} and play a unit from your opponent's starting deck.</p>
	},
	{	name: "Marching Orders",
		prov: "p8",
		type: "special",
		faction: "neutral",
		border: "gold",
		epic: true,
		src: "marching.mp4",
		tooltip: <p>Play the lowest unit from your deck.</p>
	},
	{	name: "Glorious Hunt",
		prov: "p8",
		type: "special",
		faction: "neutral",
		border: "gold",
		epic: true,
		src: "hunt.mp4",
		tooltip: <p>Destroy the unit with the highest base power.</p>
	},
	{	name: "Sabrina's Inferno",
		prov: "p8",
		type: "special",
		faction: "northern",
		border: "gold",
		epic: true,
		src: "sabrina.mp4",
		tooltip: <p>Damage each non-Specter unit by 1. If any were destroyed, repeat this ability once.</p>
	},
	{	name: "Damnation",
		prov: "p8",
		type: "special",
		faction: "syndicate",
		border: "gold",
		epic: true,
		src: "damnation.mp4",
		tooltip: <p>Damage 3 adjacent enemy units by 2.<br/>{deathblow}: For every enemy unit destroyed, {spawn} a Firesworn Zealot on the opposite row.</p>
	},
	{	name: "Vandergrift's Blade",
		prov: "p8",
		type: "artifact",
		faction: "northern",
		border: "gold",
		epic: true,
		src: "blade.mp4",
		tooltip: <p>{deploy}: Boost an allied unit by 6. Whenever you play a Knight, boost it by 1.</p>
	},
	{	name: "Mahakam Horn",
		prov: "p8",
		type: "artifact",
		faction: "scoiatael",
		border: "gold",
		epic: true,
		src: "horn.mp4",
		tooltip: <p>{spring}: Boost adjacent units by 3.<br/>{ambush}: When your opponent passes, boost adjacent units by 4.</p>
	},
	{	name: "Jutta an Dimun",
		prov: "p8",
		type: "unit",
		strength: "12",
		faction: "skellige",
		border: "gold",
		epic: true,
		src: "jutta.mp4",
		tooltip: <p>{deploy}: If Jutta an Dimun is the highest unit, damage self by 6.</p>
	},
	{	name: "Golyat",
		prov: "p8",
		type: "unit",
		strength: "10",
		faction: "monsters",
		border: "gold",
		epic: true,
		src: "golyat.mp4",
		tooltip: <p>{deathwish}: Your opponent {summon} the highest unit from their deck on the opposite row.</p>
	},
	{	name: "Foltest's Pride",
		prov: "p8",
		type: "unit",
		strength: "6",
		faction: "northern",
		border: "gold",
		epic: true,
		src: "pride.mp4",
		tooltip: <p>{zeal}.<br/>{order} ({melee}): Damage a unit by 1.<br/>{charge}: 1.<br/>{crew}: Damage a unit by 2 instead.</p>
	},
	{	name: "Svanrige Tuirseach",
		prov: "p8",
		type: "unit",
		strength: "6",
		faction: "skellige",
		border: "gold",
		epic: true,
		src: "svanrige.mp4",
		tooltip: <p>{deploy}, {bloodthirst} 3: Boost self by 5.</p>
	},
	{	name: "Operator",
		prov: "p8",
		type: "unit",
		strength: "5",
		faction: "neutral",
		border: "gold",
		epic: true,
		src: "operator.mp4",
		tooltip: <p>{deploy}: {spawn} and {summon} a base copy of a bronze unit from your hand to this row on each player's side.</p>
	},
	{	name: "Vandergrift",
		prov: "p8",
		type: "unit",
		strength: "5",
		faction: "northern",
		border: "gold",
		legendary: true,
		src: "vandergrift.mp4",
		tooltip: <p>{shield}. {resilience}.</p>
	},
	{	name: "Toruviel",
		prov: "p8",
		type: "unit",
		strength: "5",
		faction: "scoiatael",
		border: "gold",
		epic: true,
		src: "toruviel.mp4",
		tooltip: <p>{deploy} ({melee}): Damage enemy units at the ends of a row by 2.<br/>{deploy} ({ranged}): Damage all enemy units on a row by 1.</p>
	},
	{	name: "Aeliren",
		prov: "p8",
		type: "unit",
		strength: "5",
		faction: "scoiatael",
		border: "gold",
		legendary: true,
		src: "aelirenn.mp4",
		tooltip: <p>If on turn end you control 5 or more allied Elf units, {summon} this unit from your deck to the melee row.</p>
	},
	{	name: "Pavko Gale",
		prov: "p8",
		type: "unit",
		strength: "5",
		faction: "scoiatael",
		border: "gold",
		epic: true,
		src: "pavko.mp4",
		tooltip: <p>{order} ({ranged}): Damage a unit by 1. {cooldown}: 1. If you control only Scoiatael units, damage a unit by 2 instead.</p>
	},
	{	name: "Chironex",
		prov: "p8",
		type: "unit",
		strength: "4",
		faction: "neutral",
		border: "gold",
		legendary: true,
		src: "chironex.mp4",
		tooltip: <p>{deploy}: Damage a unit by 3. If you control Unicorn, double that amount.</p>
	},
	{	name: "Hefty Helge",
		prov: "p8",
		type: "unit",
		strength: "4",
		faction: "nilfgaard",
		border: "gold",
		epic: true,
		src: "helge.mp4",
		tooltip: <p>{shield}.<br/>{order}: Damage a unit by 2.<br/>{charge}: 1.<br/>Gain 1 {charge} whenever you play a Tactic.</p>
	},
	{	name: "Dennis Helge",
		prov: "p8",
		type: "unit",
		strength: "4",
		faction: "scoiatael",
		border: "gold",
		epic: true,
		src: "dennis.mp4",
		tooltip: <p>{deploy} ({melee}): Boost adjacent units by 2.<br/>{deploy} ({ranged}): Boost all other units on this row by 1.</p>
	},
	{	name: "Dire Mutated Hound",
		prov: "p8",
		type: "unit",
		strength: "4",
		faction: "syndicate",
		border: "gold",
		epic: true,
		src: "hound.mp4",
		tooltip: <p>{barricade}: At the end of every allied turn, boost self 2.<br/>{fee} 4: Gain 1 Armor.</p>
	},
	{	name: "Fransic Bedlam",
		prov: "p8",
		type: "unit",
		strength: "4",
		faction: "syndicate",
		border: "gold",
		epic: true,
		src: "bedlam.mp4",
		tooltip: <p>Every allied turn, on turn end, boost the lowest unit in your hand by 1.</p>
	},
	{	name: "Boris",
		prov: "p8",
		type: "unit",
		strength: "3",
		faction: "syndicate",
		border: "gold",
		epic: true,
		src: "boris.mp4",
		tooltip: <p>{deploy}: Damge an enemy unit by 3.<br/>{deathblow}: Gain 3 {coins}.</p>
	},
	{	name: "Menno Coehoorn",
		prov: "p8",
		type: "unit",
		strength: "2",
		faction: "nilfgaard",
		border: "gold",
		legendary: true,
		src: "coehoorn.mp4",
		tooltip: <p>{deploy} ({ranged}): Play a Tactic card from your deck.</p>
	},
	{	name: "John Natalis",
		prov: "p8",
		type: "unit",
		strength: "2",
		faction: "northern",
		border: "gold",
		legendary: true,
		src: "natalis.mp4",
		tooltip: <p>{deploy} ({melee}): Play a Warfare card from your deck.</p>
	},
	{	name: "Ferko the Sculptor",
		prov: "p8",
		type: "unit",
		strength: "2",
		faction: "syndicate",
		border: "gold",
		legendary: true,
		src: "ferko.mp4",
		tooltip: <p>{deploy} ({melee}): Play a Crime card from your deck.</p>
	},

	{	name: "Tavern Brawl",
		prov: "p7",
		type: "special",
		faction: "syndicate",
		border: "gold",
		epic: true,
		src: "brawl.mp4",
		tooltip: <p>Force an enemy unit to {duel} an adjacent unit.</p>
	},
	{	name: "Serpent Trap",
		prov: "p7",
		type: "artifact",
		faction: "scoiatael",
		border: "gold",
		epic: true,
		src: "serpent.mp4",
		tooltip: <p>{ambush}: After your opponent plays a special card, destroy the enemy unit with the highest power.</p>
	},
	{	name: "Tesham Mutha Sword",
		prov: "p7",
		type: "artifact",
		faction: "neutral",
		border: "gold",
		legendary: true,
		src: "teshamSword.mp4",
		tooltip: <p>{deploy}: Damage an enemy unit by 5. If it has a {shield}, destroy it instead.</p>
	},
	{	name: "Wyvern Scale Shield",
		prov: "p7",
		type: "artifact",
		faction: "neutral",
		border: "bronze",
		rare: true,
		src: "shield.mp4",
		tooltip: <p>{zeal}<br/>{order}: Boost an allied unit by 1.<br/>{charge}: 4.<br/>Limit 1 {charge} per turn.</p>
	},
	{	name: "Mastercrafted Spear",
		prov: "p7",
		type: "artifact",
		faction: "neutral",
		border: "bronze",
		rare: true,
		src: "spear.mp4",
		tooltip: <p>{zeal}<br/>{order}: Damage an enemy unit by 1.<br/>{charge}: 4.<br/>Limit 1 {charge} per turn.</p>
	},
	{	name: "Imperial Manticore",
		prov: "p7",
		type: "unit",
		strength: "5",
		faction: "monsters",
		border: "gold",
		epic: true,
		src: "manticore.mp4",
		tooltip: <p>{deathwish}: Destroy the lowest enemy.</p>
	},
	{	name: "False Ciri",
		prov: "p7",
		type: "unit",
		strength: "5",
		faction: "nilfgaard",
		border: "gold",
		epic: true,
		src: "falseCiri.mp4",
		tooltip: <p>{deploy} ({melee}): Move an enemy unit to the other row.<br/>{deploy} ({ranged}): Boost an Agent by 3.</p>
	},
	{	name: "Margarita Laux-Antille",
		prov: "p7",
		type: "unit",
		strength: "5",
		faction: "northern",
		border: "gold",
		epic: true,
		src: "margarita.mp4",
		tooltip: <p>{zeal}.<br/>{order}: Lock an enemy unit.</p>
	},
	{	name: "Voymir",
		prov: "p7",
		type: "unit",
		strength: "5",
		faction: "northern",
		border: "gold",
		epic: true,
		src: "voymir.mp4",
		tooltip: <p>{deploy}: Boost an allied unit and its copies by 1 and give them 1 {armor}.</p>
	},
	{	name: "Ida Emean aep Sivney",
		prov: "p7",
		type: "unit",
		strength: "5",
		faction: "scoiatael",
		border: "gold",
		epic: true,
		src: "ida.mp4",
		tooltip: <p>{deploy} ({melee}): {purify} a unit.<br/>{deploy} ({ranged}): Give an allied unit {vitality} for 4 turns.</p>
	},
	{	name: "Axel Three-Eyes",
		prov: "p7",
		type: "unit",
		strength: "5",
		faction: "skellige",
		border: "gold",
		epic: true,
		src: "axel.mp4",
		tooltip: <p>{deploy} ({melee}): {spawn} a Crow in this row.<br/>{deploy} ({ranged}): Boost self by 1 for each allied Beast.</p>
	},
	{	name: "Adalbertus Kalkstein",
		prov: "p7",
		type: "unit",
		strength: "5",
		faction: "syndicate",
		border: "gold",
		epic: true,
		src: "kalkstein.mp4",
		tooltip: <p>{profit} 2.<br/>{fee} 2: {purify} a unit.</p>
	},
	{	name: "Gael",
		prov: "p7",
		type: "unit",
		strength: "4",
		faction: "monsters",
		border: "gold",
		epic: true,
		src: "gael.mp4",
		tooltip: <p>{deploy} ({melee}): Damage an enemy unit by 1. IF it's {bleeding} deal 3 damage instead.<br/>{deathblow}: Boost self by the destroyed unit's base power.</p>
	},
	{	name: "Vreemde",
		prov: "p7",
		type: "unit",
		strength: "4",
		faction: "nilfgaard",
		border: "gold",
		epic: true,
		src: "vreemde.mp4",
		tooltip: <p>{deploy}: Boost an allied Soldier and copies of it by 2.</p>
	},
	{	name: "Ulfhedinn",
		prov: "p7",
		type: "unit",
		strength: "4",
		faction: "skellige",
		border: "gold",
		epic: true,
		src: "ulfhedinn.mp4",
		tooltip: <p>{deploy} ({melee}): Damage an enemy unit by half its current power.</p>
	},
	{	name: "Saul de Navarette",
		prov: "p7",
		type: "unit",
		strength: "4",
		faction: "syndicate",
		border: "gold",
		epic: true,
		src: "saul.mp4",
		tooltip: <p>{hoard} 3: At the end of your turn, boost self by 1.<br/>{hoard} 6: At the end of your turn, boost self by 2 instead.<br/>{hoard} 9: At the end of your turn, boost self by 3 instead.</p>
	},
	{	name: "Werecat",
		prov: "p7",
		type: "unit",
		strength: "3",
		faction: "monsters",
		border: "gold",
		epic: true,
		src: "werecat.mp4",
		tooltip: <p>{thrive}.<br/>{deploy}: Damage all enemy units on the opposite row by 1.<br/>{deathwish}: Repeat the {deploy} ability.</p>
	},

	{	name: "White Frost",
		prov: "p6",
		type: "special",
		faction: "neutral",
		border: "gold",
		epic: true,
		src: "whiteFrost.mp4",
		tooltip: <p>Destroy all Artifacts.</p>
	},
	{	name: "Sangreal",
		prov: "p6",
		type: "special",
		faction: "neutral",
		border: "gold",
		epic: true,
		src: "sangreal.mp4",
		tooltip: <p>Boost a unit by 6 and give it a {shield}.</p>
	},
	{	name: "Parasite",
		prov: "p6",
		type: "special",
		faction: "monsters",
		border: "gold",
		epic: true,
		src: "parasite.mp4",
		tooltip: <p>Damage an enemy unit by 6, or boost an allied unit by 6.</p>
	},
	{	name: "Reinforcements",
		prov: "p6",
		type: "special",
		faction: "northern",
		border: "gold",
		epic: true,
		src: "reinforcements.mp4",
		tooltip: <p>{spawn} and play a base copy of bronze allied unit.</p>
	},
	{	name: "Bloody Flail",
		prov: "p6",
		type: "special",
		faction: "northern",
		border: "gold",
		epic: true,
		src: "flail.mp4",
		tooltip: <p>Give an enemy unit {bleeding} for 8 turns.<br/>For each Soldier you control, decrease the {bleeding} duration by 1 and damage that unit by 1 instead.</p>
	},
	{	name: "Delirium",
		prov: "p6",
		type: "special",
		faction: "skellige",
		border: "gold",
		epic: true,
		src: "delirium.mp4",
		tooltip: <p>Split 6 damage randomly between all units on an enemy row.</p>
	},
	{	name: "Restore",
		prov: "p6",
		type: "special",
		faction: "skellige",
		border: "gold",
		epic: true,
		src: "restore.mp4",
		tooltip: <p>{heal} an allied unit, then boost it by the amount it was healed.</p>
	},
	{	name: "Pickpocket",
		prov: "p6",
		type: "special",
		faction: "syndicate",
		border: "gold",
		epic: true,
		src: "pickpocket.mp4",
		tooltip: <p>{profit} 7.</p>
	},
	{	name: "Experimental Remedy",
		prov: "p6",
		type: "special",
		faction: "nilfgaard",
		border: "bronze",
		epic: true,
		src: "remedy.mp4",
		tooltip: <p>Play a Bronze unit from your opponent's graveyard.</p>
	},
	{	name: "Pitfall Trap",
		prov: "p6",
		type: "artifact",
		faction: "scoiatael",
		border: "gold",
		epic: true,
		src: "pitfall.mp4",
		tooltip: <p>{ambush}: After your opponent plays a card, randomly split damage equal to its provision cost between all enemy.</p>
	},
	{	name: "Crushing Trap",
		prov: "p6",
		type: "artifact",
		faction: "scoiatael",
		border: "bronze",
		epic: true,
		src: "crushing.mp4",
		tooltip: <p>{spring}: Damage all units an a row by 1.<br/>{ambush}: After 2 turns, at the end of your turn, damage all enemy units on the row with the most units by 2.</p>
	},

	{	name: "Paulie Dahlberg",
		prov: "p6",
		type: "unit",
		strength: "6",
		faction: "scoiatael",
		border: "gold",
		epic: true,
		src: "paulie.mp4",
		tooltip: <p>{deploy} ({melee}): Move an allied unit to the other row.<br/>{deploy} ({ranged}): Give an allied unit 2 {armor}.</p>
	},
	{	name: "Heymaey Flaminica",
		prov: "p6",
		type: "unit",
		strength: "6",
		faction: "skellige",
		border: "gold",
		epic: true,
		src: "flaminica.mp4",
		tooltip: <p>At the end of your turn, {heal} all other units on this row by 1.</p>
	},
	{	name: "Whoreson's Freak Show",
		prov: "p6",
		type: "unit",
		strength: "6",
		faction: "syndicate",
		border: "gold",
		epic: true,
		src: "freak.mp4",
		tooltip: <p>{insanity}.<br/>{fee} 1: Give an enemy unit {bleeding} for 1 turn. If {insanity} was used, damage a random enemy unit by 1 instead.</p>
	},
	{	name: "Udalryk an Brokvar",
		prov: "p6",
		type: "unit",
		strength: "6",
		faction: "skellige",
		border: "gold",
		epic: true,
		src: "udalryk.mp4",
		tooltip: <p>{order}: Damage a unit by 1.<br/>{charge}: 3.<br/>{bloodthirst} 2: Gain {zeal}.</p>
	},
	{	name: "Vincent Meis",
		prov: "p6",
		type: "unit",
		strength: "6",
		faction: "northern",
		border: "gold",
		epic: true,
		src: "meis.mp4",
		tooltip: <p>{zeal}.<br/>{order} ({melee}): Set the power of a non-boosted enemy to 1.</p>
	},
	{	name: "Barbegazi",
		prov: "p6",
		type: "unit",
		strength: "6",
		faction: "monsters",
		border: "bronze",
		rare: true,
		src: "barbegazi.mp4",
		tooltip: <p>{order}: {consume} an allied unit.<br/>{charge}: 2.</p>
	},
	{	name: "Viper Witcher",
		prov: "p6",
		type: "unit",
		strength: "4",
		faction: "nilfgaard",
		border: "bronze",
		rare: true,
		src: "viperWitcher.mp4",
		tooltip: <p>{deploy}: {reveal} the top card from your opponent's deck and {banish} it.</p>
	},
	{	name: "Blue Stripes Commando",
		prov: "p6",
		type: "unit",
		strength: "4",
		faction: "northern",
		border: "bronze",
		rare: true,
		src: "commando.mp4",
		tooltip: <p>{order}: {summon} all copies of this unit from your deck to this row.</p>
	},
	{	name: "Temerian Drummer",
		prov: "p6",
		type: "unit",
		strength: "4",
		faction: "northern",
		border: "bronze",
		usual: true,
		src: "drummer.mp4",
		tooltip: <p>Every allied turn, on turn end, boost the unit to the right by 1.</p>
	},
	{	name: "Hawker Smuggler",
		prov: "p6",
		type: "unit",
		strength: "4",
		faction: "scoiatael",
		border: "bronze",
		rare: true,
		src: "smuggler.mp4",
		tooltip: <p>{melee}: Every allied turn, on turn end, boost a random unit in your hand by 1.</p>
	},
	{	name: "An Craite Greatsword",
		prov: "p6",
		type: "unit",
		strength: "4",
		faction: "skellige",
		border: "bronze",
		rare: true,
		src: "greatsword.mp4",
		tooltip: <p>Whenever an enemy unit on the opposite row takes damage, boost self by 1.</p>
	},
	{	name: "Daerlan Soldier",
		prov: "p6",
		type: "unit",
		strength: "3",
		faction: "nilfgaard",
		border: "bronze",
		rare: true,
		src: "daerlan.mp4",
		tooltip: <p>{deploy}: {spawn} a base copy of this unit and {summon} it to this row.</p>
	},
	{	name: "Impera Brigade",
		prov: "p6",
		type: "unit",
		strength: "3",
		faction: "nilfgaard",
		border: "bronze",
		rare: true,
		src: "brigade.mp4",
		tooltip: <p>{deploy} ({melee}): {summon} all copies of this unit from your deck to this row.</p>
	},
	{	name: "Witch Hunter Executioner",
		prov: "p6",
		type: "unit",
		strength: "3",
		faction: "syndicate",
		border: "bronze",
		rare: true,
		src: "executioner.mp4",
		tooltip: <p>{profit} 2.<br/>{fee} 1: GGive an enemy unit {bleeding} fro 1 turn. If it has a {bounty}, damage it by 1 instead.</p>
	},

	{	name: "Red Haze",
		prov: "p5",
		type: "special",
		faction: "neutral",
		border: "bronze",
		usual: true,
		src: "haze.mp4",
		tooltip: <p>Choose an enemy unit, then damage one adjacent enemy unit by its power.</p>
	},
	{	name: "Predatory Dive",
		prov: "p5",
		type: "special",
		faction: "monsters",
		border: "bronze",
		usual: true,
		src: "predatory.mp4",
		tooltip: <p>Each player destroys their lowest unit.</p>
	},
	{	name: "Imperia diplomacy",
		prov: "p5",
		type: "special",
		faction: "nilfgaard",
		border: "bronze",
		rare: true,
		src: "diplomacy.mp4",
		tooltip: <p>{create} and play a bronze card from your opponent's faction.</p>
	},
	{	name: "Bombardment",
		prov: "p5",
		type: "special",
		faction: "northern",
		border: "bronze",
		usual: true,
		src: "bombardment.mp4",
		tooltip: <p>Split 4 damage rondomly between all enemy units. Increase the damage by 1 for  each Sige Engine you control.</p>
	},
	{	name: "Forbidden Magic",
		prov: "p5",
		type: "special",
		faction: "northern",
		border: "bronze",
		rare: true,
		src: "magic.mp4",
		tooltip: <p>Damage an enemy unit by 2.<br/>{deathblow}: {spawn} a Kaedweni Revenant and {summon} it to a random allied row.</p>
	},
	{	name: "waylay",
		prov: "p5",
		type: "special",
		faction: "scoiatael",
		border: "bronze",
		rare: true,
		src: "waylay.mp4",
		tooltip: <p>Damage an enemy unit by 3.<br/>{deathblow}: {spawn} an Elven Deadeye in a random row.</p>
	},
	{	name: "Crow's-eye Rhizome",
		prov: "p5",
		type: "special",
		faction: "skellige",
		border: "bronze",
		usual: true,
		src: "rhizome.mp4",
		tooltip: <p>{spawn} 2 Crows in allied row. If you control a Druid, {spawn} 3 Crows instead.</p>
	},
	{	name: "Incinerating Trap",
		prov: "p5",
		type: "artifact",
		faction: "skellige",
		border: "bronze",
		rare: true,
		src: "incinerating.mp4",
		tooltip: <p>{spring}: Damagge a unit by 3.<br/>{ambush}: Damage the next unit your opponent plays on their side by 5.</p>
	},
	{	name: "Ard Feainn Tortoise",
		prov: "p5",
		type: "unit",
		strength: "7",
		faction: "nilfgaard",
		border: "bronze",
		rare: true,
		src: "tortoise.mp4",
		tooltip: <p>{exposed}: Boost an enemy unit with the most power by 3.</p>
	},
	{	name: "Cursed Knight",
		prov: "p5",
		type: "unit",
		strength: "6",
		faction: "northern",
		border: "bronze",
		rare: true,
		src: "cursed.mp4",
		tooltip: <p>{deploy}: Transform an allied unit that is not a Cursed Knight into a Cursed Knight without changing its power.</p>
	},
	{	name: "Slyzard",
		prov: "p5",
		type: "unit",
		strength: "5",
		faction: "monsters",
		border: "bronze",
		rare: true,
		src: "slyzard.mp4",
		tooltip: <p>{order}: {consume} an allied unit on this row.<br/>{cooldown}: 1.</p>
	},
	{	name: "Bomb Heaver",
		prov: "p5",
		type: "unit",
		strength: "4",
		faction: "neutral",
		border: "bronze",
		rare: true,
		src: "bomber.mp4",
		tooltip: <p>{deploy}: Destroy an enemy artifact.</p>
	},
	{	name: "Rotfiend",
		prov: "p5",
		type: "unit",
		strength: "4",
		faction: "monsters",
		border: "bronze",
		usual: true,
		src: "rotfiend.mp4",
		tooltip: <p>{deathwish}: Damage a random enemy unit by 4.</p>
	},
	{	name: "Slave Infantry",
		prov: "p5",
		type: "unit",
		strength: "4",
		faction: "nilfgaard",
		border: "bronze",
		usual: true,
		src: "infantry.mp4",
		tooltip: <p>{deploy}: Transform an allied unit into Slave Infantry.</p>
	},
	{	name: "Thirsty Dame",
		prov: "p5",
		type: "unit",
		strength: "4",
		faction: "nilfgaard",
		border: "bronze",
		usual: true,
		src: "thirsty.mp4",
		tooltip: <p>Whenever an enemy unit receives a status, boost self by 1.</p>
	},
	{	name: "Reinforced Ballista",
		prov: "p5",
		type: "unit",
		strength: "4",
		faction: "northern",
		border: "bronze",
		rare: true,
		src: "ballista.mp4",
		tooltip: <p>{formation}.<br/>{order}: Damage a unit by 1.<br/>{charge}: 1.<br/>{resupply}: Gain 1 {charge}.</p>
	},
	{	name: "Reinforced Trebuchet",
		prov: "p5",
		type: "unit",
		strength: "4",
		faction: "northern",
		border: "bronze",
		usual: true,
		src: "trebuchet.mp4",
		tooltip: <p>{ranged}: At the end of your turn, damage a random enemy unit on {ranged} row by 1.</p>
	},
	{	name: "Battering ram",
		prov: "p5",
		type: "unit",
		strength: "4",
		faction: "northern",
		border: "bronze",
		rare: true,
		src: "ram.mp4",
		tooltip: <p>{order} ({ranged}): Move Battering Ram to the (melee) row, then damage the highest enemy unit by 3.<br/>{crew}: Gain {zeal}.</p>
	},
	{	name: "An Craite Longship",
		prov: "p5",
		type: "unit",
		strength: "4",
		faction: "skellige",
		border: "bronze",
		rare: true,
		src: "longship.mp4",
		tooltip: <p>{melee}: Whenever your opponent plays a unit, deal 1 damage to it.</p>
	},
	{	name: "Brokvar Archer",
		prov: "p5",
		type: "unit",
		strength: "4",
		faction: "skellige",
		border: "bronze",
		rare: true,
		src: "archer.mp4",
		tooltip: <p>{melee} ({ranged}): Damage an enemy unit by the amount of damaged units on their side.</p>
	},
	{	name: "Drummond Shieldmaiden",
		prov: "p5",
		type: "unit",
		strength: "4",
		faction: "skellige",
		border: "bronze",
		rare: true,
		src: "shieldmaiden.mp4",
		tooltip: <p>When this this unit is damaged, {summon} all copies of it from your deck to this row.</p>
	},
	{	name: "Tax Collector",
		prov: "p5",
		type: "unit",
		strength: "4",
		faction: "syndicate",
		border: "bronze",
		rare: true,
		src: "collector.mp4",
		tooltip: <p>{ranged}: Every allied turn, on turn end, gain 1 {coins}.</p>
	},
	{	name: "Cutup Lackey",
		prov: "p5",
		type: "unit",
		strength: "4",
		faction: "syndicate",
		border: "bronze",
		usual: true,
		src: "lackey.mp4",
		tooltip: <p>Whenever you play a Crime card, damage a random enemy unit by 1.<br/>{bonded}: Increase the damage by 1.</p>
	},
	{	name: "Passiflora Peaches",
		prov: "p5",
		type: "unit",
		strength: "4",
		faction: "syndicate",
		border: "bronze",
		usual: true,
		src: "peaches.mp4",
		tooltip: <p>{hoard} 4: At the end of your turn, boost self by 1.</p>
	},
	{	name: "Maerolorn",
		prov: "p5",
		type: "unit",
		strength: "3",
		faction: "monsters",
		border: "bronze",
		rare: true,
		src: "maerolorn.mp4",
		tooltip: <p>{deploy}: Trigger a bronze allied unit's {deathwish} ability.</p>
	},
	{	name: "Mahakam Volunteers",
		prov: "p5",
		type: "unit",
		strength: "3",
		faction: "scoiatael",
		border: "bronze",
		rare: true,
		src: "volunteers.mp4",
		tooltip: <p>{deploy}: If there is a Dwarf on this row, {summon} a copy of this unit from your deck to this row.</p>
	},
	{	name: "Dimun Corsair",
		prov: "p5",
		type: "unit",
		strength: "3",
		faction: "skellige",
		border: "bronze",
		rare: true,
		src: "corsair.mp4",
		tooltip: <p>{zeal}. {order} ({melee}): Give an enemy unit {bleeding} for 2 turns. {cooldown}: 2. Whenever you play a Ship, decrease {cooldown} by 1.</p>
	},
	{	name: "Heymay Herbalist",
		prov: "p5",
		type: "unit",
		strength: "2",
		faction: "skellige",
		border: "bronze",
		usual: true,
		src: "herbalist.mp4",
		tooltip: <p>{deploy} ({ranged}): {heal} an allied unit by 3 and boost it by 3.</p>
	},

	{	name: "Golden Froth",
		prov: "p4",
		type: "special",
		faction: "neutral",
		border: "bronze",
		usual: true,
		src: "froth.mp4",
		tooltip: <p>Boost 3 adjacent units by 2.</p>
	},
	{	name: "Bloody Good Fun",
		prov: "p4",
		type: "special",
		faction: "neutral",
		border: "bronze",
		usual: true,
		src: "bloodyGood.mp4",
		tooltip: <p>{profit} 4.<br/>Spend all your {coins} and damage an enemy by the same amount.</p>
	},
	{	name: "Wagon",
		prov: "p4",
		type: "unit",
		strength: "4",
		faction: "neutral",
		border: "bronze",
		usual: true,
		src: "wagon.mp4",
		tooltip: <p>{deploy}: If you control a Bandit, gain {zeal}.<br/>{order}: Give an allied unit 3 {armor}.</p>
	},
	{	name: "Cockatrice",
		prov: "p4",
		type: "unit",
		strength: "4",
		faction: "monsters",
		border: "bronze",
		usual: true,
		src: "cockatrice.mp4",
		tooltip: <p>{deploy}: Damage an enemy unit by 1 for each adjacent Beast.</p>
	},
	{	name: "Deithwen Arbalest",
		prov: "p4",
		type: "unit",
		strength: "4",
		faction: "nilfgaard",
		border: "bronze",
		usual: true,
		src: "arbalest.mp4",
		tooltip: <p>{deploy}: Damage an enemy unit by 1 for each adjacent Beast.</p>
	},
	{	name: "Fangs of the Empire",
		prov: "p4",
		type: "unit",
		strength: "4",
		faction: "nilfgaard",
		border: "bronze",
		usual: true,
		src: "fang.mp4",
		tooltip: <p>{deploy}: Give an enemy unit {poison}.</p>
	},
	{	name: "Aedirnian Mauler",
		prov: "p4",
		type: "unit",
		strength: "4",
		faction: "northern",
		border: "bronze",
		rare: true,
		src: "mauler.mp4",
		tooltip: <p>{order} ({melee}): Damage an enemy unit by 2.</p>
	},
	{	name: "Kaedweni Knight",
		prov: "p4",
		type: "unit",
		strength: "4",
		faction: "northern",
		border: "bronze",
		rare: true,
		src: "knight.mp4",
		tooltip: <p>When played or {summon} from the deck, boost self by 3.</p>
	},
	{	name: "Pyrotechnician",
		prov: "p4",
		type: "unit",
		strength: "4",
		faction: "scoiatael",
		border: "bronze",
		usual: true,
		src: "pyrotechnician.mp4",
		tooltip: <p>{order}: Damage a random enemy unit and self by 4.</p>
	},
	{	name: "Savage Bear",
		prov: "p4",
		type: "unit",
		strength: "4",
		faction: "skellige",
		border: "bronze",
		usual: true,
		src: "bear.mp4",
		tooltip: <p>{zeal}.<br/>{deploy}: Gain 1 {charge} for each Savage Bear in your graveyard.<br/>{order}: Give {bleeding} 2 to an enemy unit.<br/>{charge}: 1.</p>
	},
	{	name: "Tuirseach Bearmaster",
		prov: "p4",
		type: "unit",
		strength: "4",
		faction: "skellige",
		border: "bronze",
		rare: true,
		src: "bearmaster.mp4",
		tooltip: <p>{zeal}.<br/>{deploy}: Give an allied Beast {vitality} for 3 turns.<br/>{bonded}: Boost an allied Beast by 3 instead.</p>
	},
	{	name: "Heymaey Protector",
		prov: "p4",
		type: "unit",
		strength: "4",
		faction: "skellige",
		border: "bronze",
		usual: true,
		src: "protector.mp4",
		tooltip: <p>{zeal}.<br/>Whenever an adjacent unit takes damage, boost self by 1.</p>
	},
	{	name: "Witch Hunter",
		prov: "p4",
		type: "unit",
		strength: "4",
		faction: "syndicate",
		border: "bronze",
		rare: true,
		src: "witchHunter.mp4",
		tooltip: <p>{deploy}: Place a {bounty} on an enemy unit.</p>
	},
	{	name: "Wild Hunt Navigator",
		prov: "p4",
		type: "unit",
		strength: "3",
		faction: "monsters",
		border: "bronze",
		usual: true,
		src: "navigator.mp4",
		tooltip: <p>{deploy}: Boost an allied unit by 1.<br/>{dominance}: Boost it by 3 instead.</p>
	},
	{	name: "Magne Division",
		prov: "p4",
		type: "unit",
		strength: "3",
		faction: "nilfgaard",
		border: "bronze",
		usual: true,
		src: "magne.mp4",
		tooltip: <p>Every allied turn, on turn end, boost self by 1 if this is the only card on this row.</p>
	},
	{	name: "Kaedweni Sergeant",
		prov: "p4",
		type: "unit",
		strength: "3",
		faction: "northern",
		border: "bronze",
		usual: true,
		src: "sergeant.mp4",
		tooltip: <p>{zeal}.<br/>{order}: Boost an allied unit by 1.<br/>{charge}: 2.</p>
	},
	{	name: "Mutated Hounds",
		prov: "p4",
		type: "unit",
		strength: "3",
		faction: "syndicate",
		border: "bronze",
		rare: true,
		src: "hounds.mp4",
		tooltip: <p>{deploy} ({melee}): Give an enemy unit {bleeding} for 2 turns.<br/>{deploy} ({ranged}): {poison} a unit.</p>
	},
	{	name: "Scoia'tael Neophyte",
		prov: "p4",
		type: "unit",
		strength: "2",
		faction: "scoiatael",
		border: "bronze",
		rare: true,
		src: "neophyte.mp4",
		tooltip: <p>{deploy}: {spawn} and {summon} a base copy of this unit to the other allied row.</p>
	},
	{	name: "Dwarven Agitator",
		prov: "p4",
		type: "unit",
		strength: "2",
		faction: "scoiatael",
		border: "bronze",
		rare: true,
		src: "agitator.mp4",
		tooltip: <p>{deploy} ({ranged}): Boost a Dwarf in your hand by 2.</p>
	},
	{	name: "Nekker",
		prov: "p4",
		type: "unit",
		strength: "1",
		faction: "monsters",
		border: "bronze",
		rare: true,
		src: "nekker.mp4",
		tooltip: <p>{thrive}.<br/>{deploy}: {spawn} a base copy of this unit and Summon it to this row.</p>
	},
];

export default CARD_INFO_ARRAY;